### ISSUE TITLE
Account type selection after new account generation appears broken

### ISSUE THREAD

**Issue by smeddinck** [Mooqita/worklearn#3]
On most recent chrome
running local build
checkout of worklearn from today

![i2 pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/1244350/30346998-781f79b8-97bf-11e7-943e-38e119074f9e.jpg)

**Comment by smeddinck** [comment]
With trial and error I can select learner and organization but not educator

**Comment by smeddinck** [comment]
appears fixed now but leaving this open until permission errors are sorted out..
also @Markus-Mooqita: is the inability to select "educator"  deliberate?

**Comment by Markus-Mooqita** [comment]
Yes we do not have an educator interface yet.
